### PR TITLE
[Feature] Pseudorandom

### PR DESCRIPTION
**Pull request by LYZhelloworld**
# Changes

1. Added pseudorandom for roulette **per group**. The probability of the `rand` will be decreased a little bit when it is chosen, and the probabilities of other numbers will increase.
2. Added pseudorandom for missing probability **per group**. The probability will increase a bit if the previous shot did not miss, and will reset when it missed.

### CODE REVIEW

**Comment by MistEO** [comment]
牛牛有很多群，随机数不应该有状态，或为每个群单独区分状态

**Comment by LYZhelloworld** [comment]
> 牛牛有很多群，随机数不应该有状态，或为每个群单独区分状态

Noted. Will fix in the following commits soon.

**Comment by MistEO** [comment]
> > 牛牛有很多群，随机数不应该有状态，或为每个群单独区分状态
> 
> Noted. Will fix in the following commits soon.

同时牛牛有很多账号登陆在同一个进程中，应为每个群的不同账号区分状态。

另外还是因为群多，尽量减少 try 和锁的粒度，有点地方可以靠 check 来回避的，没有 try 的必要

**Comment by LYZhelloworld** [comment]
Added probabilities per group. Now each group has their own independent probability values.

概率现在分群存储，每个群拥有独立的概率。

**Comment by MistEO** [comment]
Merged, Thanks for your contribution ✿✿ヽ(°▽°)ノ✿

**Pull request merged**
